config/routes.rb
Rails.application.routes.draw do

  resources :songs
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/song.rb
class Song < ActiveRecord::Base
  # validates :title, presence: true
  # validates :artist, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  # validates :artist, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = "Invalid login dummy!"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Successfully logged out."
    redirect_to login_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # before_filter :some_method
  #
  # def some_method
  #   puts "this goes before every method"
  # end


  def index
    session[:counter] ||= 0
    @counter = session[:counter] += 1
    @songs = Song.all
  end

  def new
    #can be empty b/c we don't need to gather data
    @song = Song.new # add to use partials
  end


  def show
    @song = Song.find(params[:id])
  end

  def create
    #Song.create(params[:song])
    song = Song.new(song_params)
    #based on validations
    if song.save
      redirect_to song_path(song)
    else
      # render 'new' both work symbol is used more
      render :new #render the new page(create page) again
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private
  # sets strong params
  def song_params
    params.require(:song).permit(:title, :artist)
  end
end


#
#
# class SongsController < ApplicationController
#   def index
#     @songs = Song.all
#   end
#
#   def show
#     @song = Song.find(params[:id])
#   end
#
#   def new
#     @song = Song.new
#   end
#
#   def create
#
#     #below is the actual way
#     song = Song.new(song_params)
#     if song.save
#       redirect_to song_path(song) #or just type song
#     else
#       render :new
#     end
#   end
#
#   def edit
#     @song = Song.find(params[:id])
#   end
#
#   def update
#     @song = Song.find(params[:id])
#     if @song.update(song_params)
#       redirect_to song_path(@song)
#     else
#       render :edit
#     end
#   end
#
#   def destroy
#     @song = Song.find(params[:id])
#     @song.destroy
#     redirect_to songs_path
#   end
#
#   private
#
#   def song_params
#     params.require(:song).permit(:title, :artist)
#   end
#
#
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user #user_path(@user)
    else
      flash[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end


  private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %> <!-- <form class="" action="/songs" method="post"> -->
  <%= f.text_field :title, value: "title" %> <!-- <input type="text" name="song[title]"> -->
  <%= f.text_field :artist, placeholder: "artist" %> <!-- <input type="text" name="song[artist]"> -->
  <%= f.submit %> <!-- <input type="submit" value="Create song"> -->
<% end %> <!--</form>-->

app/views/songs/edit.html.erb
<h1>test</h1>

<!-- <form class="" action="/songs" method="post">
  <input type="text" name="song[title]">
  <input type="text" name="song[artist]">
  <input type="submit" value="Create song">
</form> -->

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<% @songs.each do |song| %>
  <h1><%= song.title %></h1>
  <!--(song) is id  -->
  <%= link_to song.title, song_path(song)%>
  <p><%= song.artist %></p>
<% end %>

<p><%= @counter %></p>
<!-- <a href="/songs/new">Create a new song!</a> -->
<%= link_to "Create a new song!", new_song_path, class: 'link' %>

app/views/songs/new.html.erb
<h1>test</h1>

<!-- <form class="" action="/songs" method="post">
  <input type="text" name="song[title]">
  <input type="text" name="song[artist]">
  <input type="submit" value="Create song">
</form> -->


<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1>test song </h1>

<%= @song.title %>

<!-- check rake routes to see if id is needed -->
<%= link_to "Edit", edit_song_path(@song) %>
<%= link_to "Delete", song_path(@song), method: :delete %> <!--if a prefix is not listed the last one shown travels down hence song_path -->


#if a prefix is not listed the last one shown travels down

app/views/users/index.html.erb
<h1>Test<h1>

app/views/users/new.html.erb
<div>
    <%= flash[:errors] %>
</div>

<%= form_for(@user) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Logout", logout_path, method: :delete %>

<h1>Welcome <%= current_user.first_name %></h1>